
baseurl = "https://shaswatgupta.github.io/tech"
disablePathToLower = false
languageCode = "en-us"
title = "Citadel"
theme = "Hugo-Octopress"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# Note it's not under [params] anymore
# disqusShortname = "shagup770"

# Number of blog posts in each pagination page
paginate = 6

[permalinks]
post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

[markup]
  # Default is startLevel 2 and endLevel 3, we want to render every heading
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1
  # set the Chroma highlighting options
  # https://gohugo.io/getting-started/configuration-markup/#highlight
  [markup.highlight]
    style = "solarized-dark"
  # if you want to keep using Blackfriday
  # defaultMarkdownHandler = "blackfriday"
  #   [markup.blackFriday]
  #     hrefTargetBlank = true # open links in a new tab

[params]

  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 5

  # Sidebar header - passed to markdownify so you can write markdown here
  sidebarHeader = "Who am I"

  # Sidebar text also supports markdown
  # New lines can be added with two spaces at the end of line. New paragraphs can be added with two an empty line.
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  sidebarText = """I am Shaswat, a Senior  Site Reliability Engineer at [media.net](https://careers.media.net/system-operations/site-reliability-engineer/).
    I write about system design , reverse engineering,
    Go, automation, and (obviously) SRE.
    Click on [About Me!](/about/) to know more.
  """
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = true
  sidebarMenuHeader = "Sidebar Links"

  # sidebar links
  github = "https://github.com/shaswatgupta/"
  bitbucket = ""
  twitter = "https://twitter.com/shaswat770/"
  keybase = ""
  stackoverflow = ""
  linkedin = ""
  youtube = ""
  facebook = ""
  instagram = ""

  # --- End sidebar options ---

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or set to false, then navigation menu links will open in the same window
  navigationNewWindow = true

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Shaswat Gupta"

  # This text appears in the site header under website title
  subtitle = "An invaluable library of reference."

  # Search engine URL
  searchEngineURL = "https://www.google.com/search?q=site%3Ashaswatgupta.com"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Would you like to know more? &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  # googleAnalytics = "UA-XXXXX-X"

  # Optional piwik tracking
  # [params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = "A place to blog about my journey in tech world."

  # Populate this with your own search keywords - these will appear in the meta tags
  # defaultKeywords = ["SRE" , "Reference" ]

  # CSS override files
  # Paths should be relative to the `static` directory
  # customCSS = ["css/custom.css","css/custom2.css"]

  # 404.html header and text - both support markdown
  notFoundHeader = "There's nothing here"

  notFoundText = """Please either go back or use the navigation/sidebar menus.
  """

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or Set to false to use local fonts
  # remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise the theme uses ForkAwesome local fonts.
  fontAwesome = false

  # Generate taxonomy pages
  generateTaxonomyList = true

  # This is not needed unless alphabetical sort is needed
  # sortTaxonomyAlphabetical = true

  # Twitter card config
  # Enable with this.
  # twitterCardEnabled = true
  # Don't include the @.
  # twitterCardSite =
  # twitterCardDomain = ""
  # Don't include the @.
  # twitterCardAuthor = ""

  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  # compactIndex = true

  # Set mainSections.
  # mainSections = ["post", "blog"]

# Menu
# If navigationNewWindow (under [params]) is set to true then all links except root ("/") will open in a new window
# If it does not exist or is set to false then links will open in the same window
# [[menu.main]]
#   Name = "Home Page"
#   URL = "/"
#   weight = 5

# [[menu.main]]
#   Name = "Google"
#   URL = "https://www.google.com/"
#   weight = 200

# [[menu.main]]
#   Name = "My Life"
#   URL = "/"
#   weight = 300


# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]
[[menu.sidebar]]
  Name = "Windows"
  URL = "/categories/windows/"
  weight = 1

[[menu.sidebar]]
  Name = "SRE"
  URL = "/categories/sre/"
  weight = 1

[[menu.sidebar]]
  Name = "About page"
  URL = "/about"
  weight = 1
